//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNAClient.GxService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeDetails", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class EmployeeDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/DataModel")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactTitle {
            get {
                return this.ContactTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactTitleField, value) != true)) {
                    this.ContactTitleField = value;
                    this.RaisePropertyChanged("ContactTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GxService.ISimpleService")]
    public interface ISimpleService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISimpleService/DoWork")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISimpleService/DoWork")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetMessage", ReplyAction="http://tempuri.org/ISimpleService/GetMessageResponse")]
        string GetMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetMessage", ReplyAction="http://tempuri.org/ISimpleService/GetMessageResponse")]
        System.Threading.Tasks.Task<string> GetMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/RequestReplyOperation", ReplyAction="http://tempuri.org/ISimpleService/RequestReplyOperationResponse")]
        string RequestReplyOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/RequestReplyOperation", ReplyAction="http://tempuri.org/ISimpleService/RequestReplyOperationResponse")]
        System.Threading.Tasks.Task<string> RequestReplyOperationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/RequestReplyOperationV1", ReplyAction="http://tempuri.org/ISimpleService/RequestReplyOperationV1Response")]
        DNAClient.GxService.EmployeeDetails[] RequestReplyOperationV1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/RequestReplyOperationV1", ReplyAction="http://tempuri.org/ISimpleService/RequestReplyOperationV1Response")]
        System.Threading.Tasks.Task<DNAClient.GxService.EmployeeDetails[]> RequestReplyOperationV1Async();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISimpleService/OneWayOperationDemo")]
        void OneWayOperationDemo();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISimpleService/OneWayOperationDemo")]
        System.Threading.Tasks.Task OneWayOperationDemoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetCustomerList", ReplyAction="http://tempuri.org/ISimpleService/GetCustomerListResponse")]
        DNAClient.GxService.Customer[] GetCustomerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetCustomerList", ReplyAction="http://tempuri.org/ISimpleService/GetCustomerListResponse")]
        System.Threading.Tasks.Task<DNAClient.GxService.Customer[]> GetCustomerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/AddNewCustomer", ReplyAction="http://tempuri.org/ISimpleService/AddNewCustomerResponse")]
        bool AddNewCustomer(DNAClient.GxService.Customer details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/AddNewCustomer", ReplyAction="http://tempuri.org/ISimpleService/AddNewCustomerResponse")]
        System.Threading.Tasks.Task<bool> AddNewCustomerAsync(DNAClient.GxService.Customer details);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleServiceChannel : DNAClient.GxService.ISimpleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleServiceClient : System.ServiceModel.ClientBase<DNAClient.GxService.ISimpleService>, DNAClient.GxService.ISimpleService {
        
        public SimpleServiceClient() {
        }
        
        public SimpleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GetMessage() {
            return base.Channel.GetMessage();
        }
        
        public System.Threading.Tasks.Task<string> GetMessageAsync() {
            return base.Channel.GetMessageAsync();
        }
        
        public string RequestReplyOperation() {
            return base.Channel.RequestReplyOperation();
        }
        
        public System.Threading.Tasks.Task<string> RequestReplyOperationAsync() {
            return base.Channel.RequestReplyOperationAsync();
        }
        
        public DNAClient.GxService.EmployeeDetails[] RequestReplyOperationV1() {
            return base.Channel.RequestReplyOperationV1();
        }
        
        public System.Threading.Tasks.Task<DNAClient.GxService.EmployeeDetails[]> RequestReplyOperationV1Async() {
            return base.Channel.RequestReplyOperationV1Async();
        }
        
        public void OneWayOperationDemo() {
            base.Channel.OneWayOperationDemo();
        }
        
        public System.Threading.Tasks.Task OneWayOperationDemoAsync() {
            return base.Channel.OneWayOperationDemoAsync();
        }
        
        public DNAClient.GxService.Customer[] GetCustomerList() {
            return base.Channel.GetCustomerList();
        }
        
        public System.Threading.Tasks.Task<DNAClient.GxService.Customer[]> GetCustomerListAsync() {
            return base.Channel.GetCustomerListAsync();
        }
        
        public bool AddNewCustomer(DNAClient.GxService.Customer details) {
            return base.Channel.AddNewCustomer(details);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewCustomerAsync(DNAClient.GxService.Customer details) {
            return base.Channel.AddNewCustomerAsync(details);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GxService.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ProcessReport", ReplyAction="http://tempuri.org/IReportService/ProcessReportResponse")]
        void ProcessReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/ProcessReport", ReplyAction="http://tempuri.org/IReportService/ProcessReportResponse")]
        System.Threading.Tasks.Task ProcessReportAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : DNAClient.GxService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<DNAClient.GxService.IReportService>, DNAClient.GxService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ProcessReport() {
            base.Channel.ProcessReport();
        }
        
        public System.Threading.Tasks.Task ProcessReportAsync() {
            return base.Channel.ProcessReportAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GxService.IRestfulDNA")]
    public interface IRestfulDNA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestfulDNA/RequestReplyOperation_Rest", ReplyAction="http://tempuri.org/IRestfulDNA/RequestReplyOperation_RestResponse")]
        string RequestReplyOperation_Rest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestfulDNA/RequestReplyOperation_Rest", ReplyAction="http://tempuri.org/IRestfulDNA/RequestReplyOperation_RestResponse")]
        System.Threading.Tasks.Task<string> RequestReplyOperation_RestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestfulDNA/RequestReplyOperation_RestV1", ReplyAction="http://tempuri.org/IRestfulDNA/RequestReplyOperation_RestV1Response")]
        DNAClient.GxService.EmployeeDetails[] RequestReplyOperation_RestV1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestfulDNA/RequestReplyOperation_RestV1", ReplyAction="http://tempuri.org/IRestfulDNA/RequestReplyOperation_RestV1Response")]
        System.Threading.Tasks.Task<DNAClient.GxService.EmployeeDetails[]> RequestReplyOperation_RestV1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestfulDNA/GetCustomerList_Rest", ReplyAction="http://tempuri.org/IRestfulDNA/GetCustomerList_RestResponse")]
        DNAClient.GxService.Customer[] GetCustomerList_Rest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestfulDNA/GetCustomerList_Rest", ReplyAction="http://tempuri.org/IRestfulDNA/GetCustomerList_RestResponse")]
        System.Threading.Tasks.Task<DNAClient.GxService.Customer[]> GetCustomerList_RestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestfulDNA/AddNewCustomer_Rest", ReplyAction="http://tempuri.org/IRestfulDNA/AddNewCustomer_RestResponse")]
        bool AddNewCustomer_Rest(DNAClient.GxService.Customer details);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestfulDNA/AddNewCustomer_Rest", ReplyAction="http://tempuri.org/IRestfulDNA/AddNewCustomer_RestResponse")]
        System.Threading.Tasks.Task<bool> AddNewCustomer_RestAsync(DNAClient.GxService.Customer details);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestfulDNAChannel : DNAClient.GxService.IRestfulDNA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestfulDNAClient : System.ServiceModel.ClientBase<DNAClient.GxService.IRestfulDNA>, DNAClient.GxService.IRestfulDNA {
        
        public RestfulDNAClient() {
        }
        
        public RestfulDNAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestfulDNAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestfulDNAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestfulDNAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RequestReplyOperation_Rest() {
            return base.Channel.RequestReplyOperation_Rest();
        }
        
        public System.Threading.Tasks.Task<string> RequestReplyOperation_RestAsync() {
            return base.Channel.RequestReplyOperation_RestAsync();
        }
        
        public DNAClient.GxService.EmployeeDetails[] RequestReplyOperation_RestV1() {
            return base.Channel.RequestReplyOperation_RestV1();
        }
        
        public System.Threading.Tasks.Task<DNAClient.GxService.EmployeeDetails[]> RequestReplyOperation_RestV1Async() {
            return base.Channel.RequestReplyOperation_RestV1Async();
        }
        
        public DNAClient.GxService.Customer[] GetCustomerList_Rest() {
            return base.Channel.GetCustomerList_Rest();
        }
        
        public System.Threading.Tasks.Task<DNAClient.GxService.Customer[]> GetCustomerList_RestAsync() {
            return base.Channel.GetCustomerList_RestAsync();
        }
        
        public bool AddNewCustomer_Rest(DNAClient.GxService.Customer details) {
            return base.Channel.AddNewCustomer_Rest(details);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewCustomer_RestAsync(DNAClient.GxService.Customer details) {
            return base.Channel.AddNewCustomer_RestAsync(details);
        }
    }
}
